const updateDate = "2026-05-31";
const dbData = [
    {
        "id": "1044397299286",
        "name": "【上海】2026 「良辰·声境如梦」上海音乐会（演出阵容：金弦/郑希/杨天翔/袁铭喆等）",
        "city": "上海市",
        "venue": "交通银行前滩31演艺中心 · 大剧场",
        "time": "2026.06.28 周日 19:00",
        "price_min": 188,
        "price_max": 688,
        "link": "https://detail.damai.cn/item.htm?id=1044397299286",
        "tracks": []
    },
    {
        "id": "1054028157695",
        "name": "【上海】「开小差·Space Out」许昌泰生日音乐会-【缪时客出品】",
        "city": "上海市",
        "venue": "蜚声上海PHASE LIVE HOUSE SHANGHAI",
        "time": "2026.06.18 周四 19:30",
        "price_min": 180,
        "price_max": 580,
        "link": "https://detail.damai.cn/item.htm?id=1054028157695",
        "tracks": []
    },
    {
        "id": "1046570666627",
        "name": "【上海】Best of Us：小时代音乐会·巡回首站-上海限定",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.19-06.21",
        "price_min": 180,
        "price_max": 880,
        "link": "https://detail.damai.cn/item.htm?id=1046570666627",
        "tracks": [
            "《我好想你》",
            "《时间煮雨》",
            "《不再见》",
            "《小时代》",
            "《万花瞳》",
            "《灵魂尽头》"
        ]
    },
    {
        "id": "1052293578894",
        "name": "【上海】虹猫蓝兔二十周年音乐会",
        "city": "上海市",
        "venue": "凯迪拉克·上海音乐厅-大厅",
        "time": "2026.06.20 周六 19:00",
        "price_min": 80,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1052293578894",
        "tracks": [
            "人生不过一百年",
            "心中想的还是他",
            "少侠",
            "如果",
            "幸福",
            "光明之巅",
            "孤注一掷",
            "七剑合璧",
            "正面交锋",
            "七叶花开",
            "暗战迭起",
            "东奔西顾",
            "白猫之死",
            "大奔制怒",
            "圣光初现",
            "诉",
            "摇篮曲",
            "勇气试炼",
            "寒萧对月"
        ]
    },
    {
        "id": "1051663768240",
        "name": "【上海】古典乐巨匠之夜：贝多芬传世经典音乐会《命运交响曲》",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.27 周六 19:30",
        "price_min": 108,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1051663768240",
        "tracks": [
            "C小调九段变奏曲 WoO.63",
            "《德雷斯勒九段主题变奏曲》",
            "Beethoven - 9 Variations on a March by Dressler in C Minor, WoO.63",
            "G大调小步舞曲",
            "Beethoven - Minuet in G Major, WoO.10, No.2",
            "悲怆钢琴奏鸣曲第二乐章",
            "Beethoven - Piano Sonata No.8, Op.13",
            "《Pathetique》, Mov.II",
            "贝多芬病毒",
            "Beethoven - Piano Sonata No.8, Op.13,",
            "《Pathetique》, Mov.III.",
            "降E大调七重奏",
            "Beethoven - Septet Op.20 in E flat major",
            "第五交响曲-命运",
            "Beethoven - Symphony No.5",
            "小提琴奏鸣曲-春",
            "Beethoven - Violin Sonatas No.5, Op.24 《Spring》",
            "第六号交响曲-田园",
            "Beethoven: Symphony No. 6, Op.68 《Pastoral》",
            "致爱丽丝",
            "Beethoven - Für Elise",
            "月光奏鸣曲",
            "Beethoven - Piano Sonata No.14 《Moonlight》",
            "土耳其进行曲",
            "Beethoven - Turkish Marc Op.113",
            "合唱幻想",
            "Beethoven - Choral Fantasy",
            "庄严弥撒",
            "Beethoven - Missa Solemnis",
            "欢乐颂",
            "Beethoven - Symphony No.9 in D minor, Op.125"
        ]
    },
    {
        "id": "1041906713616",
        "name": "【上海】【限时8折】歌剧魅影·悲惨世界·爱乐之城 百老汇音乐剧&好莱坞电影经典音乐会",
        "city": "上海市",
        "venue": "虹桥艺术中心",
        "time": "2026.06.05 周五 19:30",
        "price_min": 80,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1041906713616",
        "tracks": [
            "Overture - 音乐剧《歌剧魅影》序曲",
            "Singin' in the Rain - 音乐剧《雨中曲》",
            "I Dreamed a Dream - 音乐剧《悲惨世界》",
            "The Jelldiddle Ball - 音乐剧《猫》",
            "Pure Imagination - 音乐剧《查理与巧克力工厂》",
            "Mamma Mia! Medley - 音乐剧《妈妈咪呀！》组曲",
            "Solo + Whiplash - 电影《鸟人》《爆裂鼓手》组曲",
            "007 Theme - 007系列电影《007主题曲》",
            "Mission: Impossible Theme - 电影《碟中谍》主题曲",
            "City of Stars - 电影《爱乐之城》",
            "Ain't No Mountain High Enough - 电影《银河护卫队》",
            "Caravan - 电影《爆裂鼓手》"
        ]
    },
    {
        "id": "1036490996578",
        "name": "【上海】【限时8折】“热血巅峰”灌篮高手·火影忍者·海贼王 二次元神级动漫金曲演唱会",
        "city": "上海市",
        "venue": "虹桥艺术中心",
        "time": "2026.06.06 周六 15:00",
        "price_min": 80,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1036490996578",
        "tracks": [
            "黄金之风处刑曲——JoJo的奇妙冒险",
            "千本樱",
            "We are!——海贼王",
            "直到世界尽头——灌篮高手",
            "青鸟——火影忍者",
            "极乐净土",
            "Butter fly——数码宝贝",
            "魔诃的不可思议大冒险——龙珠",
            "名侦探柯南主题曲",
            "Brand new day——灌篮高手",
            "明日将近——灌篮高手",
            "Lost in paradise——咒术回战",
            "残酷天使的行动纲领——EVA新世纪福音战士",
            "曾经我也想了一百了",
            "红莲华——鬼灭之刃",
            "Only my railgun——某科学的超电磁炮"
        ]
    },
    {
        "id": "1047732785930",
        "name": "【上海】小号巨星克里斯·波提 Chris Botti 2026上海音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.11 周四 19:30",
        "price_min": 280,
        "price_max": 1280,
        "link": "https://detail.damai.cn/item.htm?id=1047732785930",
        "tracks": []
    },
    {
        "id": "1050967634705",
        "name": "【上海】《坂本龙一&久石让》经典作品音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-演奏厅",
        "time": "2026.06.19 周五 19:45",
        "price_min": 90,
        "price_max": 300,
        "link": "https://detail.damai.cn/item.htm?id=1050967634705",
        "tracks": [
            "《流动的能量》Energy Flow",
            "《雨》Rain",
            "《生命之源》Aqua",
            "《东风》Tong Poo",
            "《遮蔽的天空》The Sheltering Sky",
            "《末代皇帝》The Last Emperor",
            "《圣诞快乐，劳伦斯先生》",
            "Merry Christmas, Mr. Lawrence",
            "《孤独》Solitude",
            "《风之谷》Nausicaä of the Valley of the Wind",
            "《幽灵公主》Princess Mononoke",
            "《菊次郎的夏天》Summer",
            "《红猪》Porco Rosso",
            "《千与千寻》Spirited Away: One Summer",
            "《哈尔的移动城堡》Howl's Moving Castle",
            "《久石让作品联奏》Joe Hisaishi Song Medley",
            "-《白龙少年》The Dragon Boy",
            "-《天空之城》Castle In the Sky",
            "-《遥远的日子》The Days Long Gone",
            "-《魔女宅急便》Kiki's Delivery Service",
            "-《风之甬道》Path of the Wind",
            "-《崖上的波妞》Ponyo on the Cliff"
        ]
    },
    {
        "id": "1034729582586",
        "name": "【上海】【限时5折】“后来·十年”流行金曲榜·华语必听经典演唱会",
        "city": "上海市",
        "venue": "虹桥艺术中心",
        "time": "2026.06.06 周六 19:30",
        "price_min": 80,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1034729582586",
        "tracks": [
            "突然好想你",
            "童话",
            "爱我别走",
            "青花",
            "青苹果乐园",
            "十年",
            "伤心的人别听慢歌",
            "离开地球表面",
            "至少还有你",
            "绿光",
            "漂洋过海来看你",
            "听海",
            "红豆",
            "我们的爱",
            "后来"
        ]
    },
    {
        "id": "1034677350679",
        "name": "【上海】「多厨狂喜」白金交响乐团二次元交响音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.28 周日 14:00",
        "price_min": 99,
        "price_max": 520,
        "link": "https://detail.damai.cn/item.htm?id=1034677350679",
        "tracks": []
    },
    {
        "id": "1046497042736",
        "name": "【上海】The Andrew Show 外滩经典之夜",
        "city": "上海市",
        "venue": "大世界3楼世界盒子剧场",
        "time": "2026.06.02-06.30",
        "price_min": 280,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1046497042736",
        "tracks": [
            "Fix You (Coldplay 金曲)",
            "Volare (西班牙语舞曲)",
            "Mattinata (意大利经典民谣)",
            "Can't Help Falling in Love (吉他弹唱)",
            "千千阙歌（粤语经典）",
            "Music of the Night（《剧院魅影》选段）",
            "You Raise Me Up（励志佳作）",
            "Pure Imagination（《查理和巧克力工厂》选段）",
            "我的太阳（意大利民歌）",
            "童话（中文流行金曲）",
            "Take Me Home, Country Roads（乡村经典）",
            "Bring Him Home（《悲惨世界》选段）",
            "Viva la vida（酷感金曲）",
            "夜上海（酷感金曲）",
            "Time to Say Goodbye（波切利金曲）"
        ]
    },
    {
        "id": "1038383629598",
        "name": "【上海】无限∞咏叹——石倚洁·郭森·周正中 歌剧咏叹调专场音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.06 周六 19:30",
        "price_min": 180,
        "price_max": 680,
        "link": "https://detail.damai.cn/item.htm?id=1038383629598",
        "tracks": []
    },
    {
        "id": "1051017059150",
        "name": "【上海】国家艺术基金2025年度大型舞台剧和作品创作资助项目 致敬经典 · 逐梦苍穹 交响音乐会",
        "city": "上海市",
        "venue": "上音歌剧院·歌剧厅",
        "time": "2026.06.03 周三 19:30",
        "price_min": 30,
        "price_max": 280,
        "link": "https://detail.damai.cn/item.htm?id=1051017059150",
        "tracks": [
            "交响乐《红旗颂》",
            "小提琴协奏曲《金色的炉台》",
            "交响乐《激情燃烧的岁月》",
            "管弦乐组曲《炎黄风情》",
            "培尔金特组曲（选段）",
            "歌剧《魔笛》（选段）",
            "《匈牙利舞曲第一号》",
            "中场休息",
            "交响乐《华夏圆宇》——为管弦乐队与混声合唱而作"
        ]
    },
    {
        "id": "1035004983833",
        "name": "【上海】享誉全球的萨克斯天王 戴夫·考滋与夏日号角全明星乐团",
        "city": "上海市",
        "venue": "久事·上海商城剧院",
        "time": "2026.06.07 周日 19:30",
        "price_min": 280,
        "price_max": 1280,
        "link": "https://detail.damai.cn/item.htm?id=1035004983833",
        "tracks": []
    },
    {
        "id": "1037672258684",
        "name": "【上海】The Barricade Boys街垒男孩：伦敦音乐剧四重唱组合巡演音乐会",
        "city": "上海市",
        "venue": "北外滩友邦大剧院-大剧场",
        "time": "2026.06.25-06.28",
        "price_min": 180,
        "price_max": 880,
        "link": "https://detail.damai.cn/item.htm?id=1037672258684",
        "tracks": [
            "《我曾有梦》-选自《悲惨世界》",
            "《低头》-选自《悲惨世界》",
            "摩城经典曲目串烧",
            "童年金曲串烧",
            "《人去楼空》-选自《悲惨世界》",
            "《反抗重力》-选自《魔法坏女巫》",
            "《带他回家》-选自《悲惨世界》",
            "《妈妈咪呀！》串烧",
            "《泽西男孩》串烧",
            "《西区故事》串烧",
            "《飞翔》-迪恩·马丁",
            "《繁星》-选自《悲惨世界》",
            "英国摇滚传奇串烧",
            "《波西米亚狂想曲》-皇后乐队",
            "《扭动与呐喊》-披头士乐队",
            "《飘，裘德》-披头士乐队",
            "《只待明日》-选自《悲惨世界》"
        ]
    },
    {
        "id": "1052820171119",
        "name": "【上海】2026浦东精品剧目展演 上海音乐学院 新时代版《长征组歌》",
        "city": "上海市",
        "venue": "东方艺术中心-歌剧厅",
        "time": "2026.06.06 周六 19:15",
        "price_min": 80,
        "price_max": 80,
        "link": "https://detail.damai.cn/item.htm?id=1052820171119",
        "tracks": [
            "《红旗颂》",
            "《长征组歌》",
            "1.《告别》",
            "2.《突破封锁线》",
            "3.《遵义会议放光辉》（领唱：许洁、陈阳）",
            "4.《四渡赤水出奇兵》（领唱:陈京蔚、张功浩）",
            "5.《飞越大渡河》",
            "6.《过雪山草地》（领唱：冯浩然）",
            "7.《到吴起镇》",
            "8.《祝捷》（领唱:陈家坡）",
            "9.《报喜》（领唱:李秀英）",
            "10.《大会师》"
        ]
    },
    {
        "id": "1045906710796",
        "name": "【上海】Dee Dee Bridgewater with Helen Sung 天籁二重奏",
        "city": "上海市",
        "venue": "久事·上海商城剧院",
        "time": "2026.06.04 周四 19:30",
        "price_min": 280,
        "price_max": 1080,
        "link": "https://detail.damai.cn/item.htm?id=1045906710796",
        "tracks": []
    },
    {
        "id": "1039819497898",
        "name": "【上海】精华贝多芬——布劳蒂甘现代钢琴独奏会丨上海交响乐团音乐季",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.07 周日 19:30",
        "price_min": 100,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1039819497898",
        "tracks": [
            "贝多芬：升F大调第二十四钢琴奏鸣曲，作品78「献给泰蕾兹」",
            "贝多芬：f小调第二十三钢琴奏鸣曲，作品57「热情」",
            "贝多芬：降E大调第二十六钢琴奏鸣曲，作品81a「告别」",
            "贝多芬：c小调第三十二钢琴奏鸣曲，作品111"
        ]
    },
    {
        "id": "1037676558754",
        "name": "【上海】SUPERNOVA西区当红·伦敦西区音乐剧超新星音乐会",
        "city": "上海市",
        "venue": "上海保利大剧院-大剧场",
        "time": "2026.06.06-06.07",
        "price_min": 80,
        "price_max": 680,
        "link": "https://detail.damai.cn/item.htm?id=1037676558754",
        "tracks": [
            "Superstar",
            "万世巨星",
            "The Phantom of The Opera",
            "剧院魅影",
            "Cabaret",
            "卡巴莱",
            "Top Hat",
            "礼帽",
            "Kiss Me, Kate",
            "吻我, 凯特",
            "Frozen II",
            "冰雪奇缘2",
            "West Side Story",
            "西区故事",
            "MJ The Musical",
            "迈克尔·杰克逊",
            "Hadeastown",
            "哈迪斯城",
            "Moulin Rouge!",
            "红磨坊",
            "Six",
            "六皇后",
            "Hamilton",
            "汉密尔顿",
            "Heathers",
            "希德姐妹帮",
            "The Greatest Showman",
            "马戏之王",
            "Guys and Dolls",
            "红男绿女",
            "Wicked",
            "魔法坏女巫",
            "Evita",
            "贝隆夫人",
            "Dear Evan Hansen",
            "致埃文·汉森",
            "Les Misérables",
            "悲惨世界",
            "Tina",
            "蒂娜"
        ]
    },
    {
        "id": "1052566743058",
        "name": "【上海】上海音乐学院学科建设成果展演季 暨2026上音歌剧院春季演出季 海上非遗 民族室内乐原创作品音乐会",
        "city": "上海市",
        "venue": "贺绿汀音乐厅",
        "time": "2026.06.02 周二 19:30",
        "price_min": 30,
        "price_max": 280,
        "link": "https://detail.damai.cn/item.htm?id=1052566743058",
        "tracks": [
            "袁媛《织梦》——为琵琶与钢琴与打击乐",
            "刘聪昕《元夕》——为筝、古琴与扬琴与打击乐",
            "谢琴伟《瓷韵》——为琵琶、古琴与打击乐",
            "李谧德《灯楼》——为竹笛、唢呐、琵琶与铜琴",
            "何佳宁《千织》——为打击乐与铜琴",
            "兰逸峻《锦瑟》——为民族室内乐",
            "楼嘉《流光》——为中阮与铜琴",
            "史志珺《雨淋铃》——为柳琴与手风琴",
            "李霓霞《青铜》——为笙、古筝与打击乐",
            "林鹭磬《无界·武魂》——为民族室内乐"
        ]
    },
    {
        "id": "1031748595356",
        "name": "【上海】法国Grissini Project格里西尼乐团「幻乐交织・光影新章」2026巡回音乐会",
        "city": "上海市",
        "venue": "北外滩友邦大剧院-大剧场",
        "time": "2026.06.10 周三 19:30",
        "price_min": 100,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1031748595356",
        "tracks": [
            "史诗燃情 心跳加速",
            "俄罗斯方块",
            "Skyrim - The Dragonborn Comes",
            "上古卷轴5: 天际 - 龙裔降临",
            "What Could Have Been",
            "英雄联盟",
            "Megalovania - Undertale",
            "传说之下",
            "Gladiator - Now We are Free",
            "角斗士 - 终得自由",
            "缱绻柔情 时光慢煮",
            "Harry Potter - Hedwig's Theme",
            "海德薇主题曲",
            "Les Parapluiies de Cherbourg - I Will Wait for You",
            "瑟堡的雨伞 - 我会等你",
            "Schindler's List Theme",
            "辛德勒的名单",
            "Coco - Remember me",
            "寻梦环游记 - 请记住我",
            "The Greatest Showman - Never Enough",
            "马戏之王 - 永不止步",
            "奇幻漫游 神秘宇宙",
            "Interstellar - Cornfield Chase",
            "星际穿越 - 原野追逐",
            "指环王 - 关于霍比特人",
            "Lord of the Rings - In Dreams",
            "指环王 - 梦中",
            "Libertango",
            "自由探戈",
            "Game of Thrones - Jenny of Oldstones",
            "权力的游戏 - 旧镇的珍妮",
            "Sherlock Holmes - Discombobulate",
            "福尔摩斯 - 舞乱敌阵",
            "璀璨狂欢 金曲终章",
            "La La Land - Another Day of Sun",
            "爱乐之城 - 阳光灿烂的一天",
            "The Witcher 3 - The Wolven Storm",
            "巫师3 - 狼之风暴",
            "Pirates of the Caribbean - Davy Jones's Theme",
            "加勒比海盗 - 戴维·琼斯主题曲",
            "加勒比海盗 - 扬起船旗",
            "Pirates of the Caribbean - Hoist the Colours",
            "Pirates of the Caribbean - He's a Pirate",
            "加勒比海盗 - 他是海盗"
        ]
    },
    {
        "id": "1033301989213",
        "name": "【上海】上海爱乐乐团2025-2026音乐季 大师与经典系列 《陈燮阳与上海爱乐乐团》",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.18 周四 19:30",
        "price_min": 50,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1033301989213",
        "tracks": [
            "卡拉·卡拉耶夫：芭蕾舞剧《七美人》组曲",
            "谢尔盖·拉赫玛尼诺夫：E小调第二交响曲，作品27"
        ]
    },
    {
        "id": "1044483452462",
        "name": "【上海】「玖等的乐章」星玖 x 和音社 交响管乐动漫音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.13 周六 19:30",
        "price_min": 180,
        "price_max": 580,
        "link": "https://detail.damai.cn/item.htm?id=1044483452462",
        "tracks": [
            "DREAM SOLOISTER",
            "「吹响吧！上低音号」第一季OP",
            "普罗旺斯之风",
            "「吹响吧！上低音号」第一季插曲",
            "你是天然色",
            "「吹响吧！上低音号」第二季插曲",
            "一年之诗",
            "「吹响吧！上低音号」第三季插曲",
            "爱的决断",
            "「利兹与青鸟」插曲",
            "宝岛",
            "「吹响吧！上低音号」第三季插曲",
            "轻音少女组曲",
            "轻音永不毕业！！！",
            "——轻音少女插曲",
            "KiLLkiSS",
            "saki酱saki酱saki酱……",
            "「Bang Dream!」插曲",
            "鸟之诗",
            "我的夏天结束了",
            "——「Air」OP",
            "鬼灭之刃・无限城",
            "打架就打架 别跟我说话",
            "「鬼灭之刃」插曲",
            "欢乐斗地主",
            "十七张牌你能秒我？",
            "「欢乐斗地主」插曲"
        ]
    },
    {
        "id": "1026086739425",
        "name": "【上海】俄罗斯音乐剧双子星2.0音乐会",
        "city": "上海市",
        "venue": "美琪大戏院",
        "time": "2026.05.31 周日 14:30",
        "price_min": 199,
        "price_max": 599,
        "link": "https://detail.damai.cn/item.htm?id=1026086739425",
        "tracks": [
            "飞空逐梦",
            "哥特迷梦"
        ]
    },
    {
        "id": "1043243213222",
        "name": "【上海】20260615本杰明·赞德尔与波士顿青年爱乐乐团上海音乐会",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.15 周一 19:30",
        "price_min": 80,
        "price_max": 680,
        "link": "https://detail.damai.cn/item.htm?id=1043243213222",
        "tracks": [
            "伯恩斯坦：《坎迪德》序曲",
            "马克思·布鲁赫：g小调第一小提琴协奏曲，作品26",
            "古斯塔夫·马勒：D大调第一交响曲“巨人”"
        ]
    },
    {
        "id": "1034731286576",
        "name": "【上海】【限时5折】千与千寻 天空之城 菊次郎的夏天 久石让&宫崎骏动漫经典音乐作品演奏会",
        "city": "上海市",
        "venue": "虹桥艺术中心",
        "time": "2026.06.07 周日 15:00",
        "price_min": 80,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1034731286576",
        "tracks": [
            "1.伴随着你(独奏版)",
            "2.世界的约定",
            "3.魔女宅急便",
            "4.龙猫组曲",
            "5.幽灵公主组曲",
            "6.那个夏天",
            "7.起风了",
            "8.希达的决心",
            "9.伴随着你(融合版)",
            "10.悬崖上的金鱼姬",
            "11.再见萤火虫",
            "12.红猪",
            "13.重新开始",
            "14.妈妈",
            "15.菊次郎的夏天"
        ]
    },
    {
        "id": "1045441230310",
        "name": "【上海】《马年端午·国风新韵》民族音乐会",
        "city": "上海市",
        "venue": "上海长滩音乐厅",
        "time": "2026.06.19 周五 19:00",
        "price_min": 99,
        "price_max": 430,
        "link": "https://detail.damai.cn/item.htm?id=1045441230310",
        "tracks": [
            "《赛龙夺锦》",
            "《我的祖国》",
            "《大鱼》",
            "《春到湘江》",
            "《战马奔腾》",
            "《百鸟朝凤》",
            "《蝶恋花·答李淑一》",
            "《龙船》",
            "《十面埋伏》",
            "《茉莉芬芳》",
            "《北京喜讯到边寨》",
            "《梁山伯与祝英台》节选",
            "《赛马》",
            "《苏南小调》",
            "《花好月圆》"
        ]
    },
    {
        "id": "1044364839314",
        "name": "【上海】《江韵留声·海上金曲》上海滩经典音乐会",
        "city": "上海市",
        "venue": "上海长滩音乐厅",
        "time": "2026.06.06 周六 19:00",
        "price_min": 99,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1044364839314",
        "tracks": [
            "海上风华·旧梦开场",
            "夜上海",
            "天涯歌女",
            "甜蜜蜜",
            "我只在乎你",
            "再见我的爱人",
            "相思河畔",
            "如果没有你",
            "浦江鎏金·岁月回响",
            "上海滩",
            "问情",
            "偿还",
            "人间深情·声声入心",
            "茉莉花",
            "但愿人长久",
            "在水一方",
            "南泥湾"
        ]
    },
    {
        "id": "1047525701251",
        "name": "【上海】多瑙河之约·钢琴与小提琴二重奏音乐会",
        "city": "上海市",
        "venue": "凯迪拉克·上海音乐厅-音乐立方",
        "time": "2026.06.13 周六 14:00",
        "price_min": 80,
        "price_max": 280,
        "link": "https://detail.damai.cn/item.htm?id=1047525701251",
        "tracks": [
            "第五号匈牙利舞曲 (约瑟夫·约阿希姆改编)",
            "G大调钢琴与小提琴奏鸣曲，KV 301",
            "钢琴与小提琴叙事曲",
            "G大调小奏鸣曲，作品100",
            "小夜曲",
            "G大调第一号小提琴奏鸣曲，作品78",
            "波丽露舞曲 作品 51 No.3"
        ]
    },
    {
        "id": "1053364985393",
        "name": "【上海】【6.6 | 周六】古锣新律 ·沉浸式疗愈音乐会",
        "city": "上海市",
        "venue": "绿洲Oasis",
        "time": "2026.06.06 周六 15:00",
        "price_min": 158,
        "price_max": 188,
        "link": "https://detail.damai.cn/item.htm?id=1053364985393",
        "tracks": []
    },
    {
        "id": "1046761906317",
        "name": "【上海】民族管弦乐《唐诗·宋词两座城》",
        "city": "上海市",
        "venue": "大零号湾文化艺术中心",
        "time": "2026.05.31 周日 19:30",
        "price_min": 56,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1046761906317",
        "tracks": [
            "初逢·梦起长安",
            "相识·锦绣长安",
            "繁花·琉璃岁月",
            "惜别·忆望长安",
            "走城·宋城市井",
            "观潮·观钱塘江",
            "赏湖·梦醉西子",
            "千年之路"
        ]
    },
    {
        "id": "1019332580466",
        "name": "【上海】【端午】“沧海一声笑·铁血丹心”笑傲江湖 神雕侠侣 武侠影视金曲交响演唱会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.20 周六 19:30",
        "price_min": 100,
        "price_max": 680,
        "link": "https://detail.damai.cn/item.htm?id=1019332580466",
        "tracks": [
            "《天地孤影任我行》",
            "《沧海一声笑》",
            "《追梦人》",
            "《刀剑如梦》",
            "《天下有情人》",
            "《归去来》",
            "《英雄的黎明》",
            "《爱江山更爱美人》",
            "《江湖笑》",
            "《天涯》",
            "《叱咤红人》",
            "《笑红尘》",
            "《难念的经》",
            "《铁血丹心》",
            "《一生有意义》",
            "《世间始终你好》",
            "《男儿当自强》"
        ]
    },
    {
        "id": "1043433062696",
        "name": "【上海】“侬好·囡囡”上海童谣亲子音乐会演出",
        "city": "上海市",
        "venue": "Mbay·贝湾 bistro&bar(梅奔江景店)",
        "time": "2026.05.31 周日",
        "price_min": 120,
        "price_max": 120,
        "link": "https://detail.damai.cn/item.htm?id=1043433062696",
        "tracks": [
            "喜欢上海的理由",
            "Me More Say",
            "老底子的味道",
            "Yummy Yummy 就是好吃",
            "垃圾分类再垃圾倒",
            "蟋蟀",
            "鹅鹅鹅",
            "申情申音",
            "上马 Superstar"
        ]
    },
    {
        "id": "1006248850118",
        "name": "【上海】【奇妙嘿夜】“海上钢琴师”“爱乐之城”“世界赠予我的”曲目主题奇妙嘿夜烛光音乐会钢琴&大提琴",
        "city": "上海市",
        "venue": "青春无限音乐厅-上海广场店",
        "time": "2026.06.06-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=1006248850118",
        "tracks": [
            "La leggenda del pianista sull'oceano",
            "Farewell Letter",
            "Flower Dance",
            "Salut d'Amour",
            "Golden Hour",
            "Ave Maria",
            "Nuovo cinema Paradiso",
            "City of Stars",
            "The Myth",
            "The Swan",
            "The Rain",
            "Tragedy",
            "He's a Pirate",
            "What the World Gives Me"
        ]
    },
    {
        "id": "1022018193641",
        "name": "【上海】《后来•遇见》籁之音歌行合唱团流行经典歌曲合唱音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.19-06.21",
        "price_min": 100,
        "price_max": 680,
        "link": "https://detail.damai.cn/item.htm?id=1022018193641",
        "tracks": [
            "爱",
            "雪落下的声音",
            "西风",
            "勇气",
            "身骑白马",
            "山中月",
            "花儿与少年",
            "光亮",
            "凤凰花开的路口",
            "遇见",
            "潺洋过海来看你",
            "是否",
            "一路生花",
            "再回首",
            "后来"
        ]
    },
    {
        "id": "1041010456246",
        "name": "【上海】让-艾弗兰·巴维钢琴独奏会：拉威尔钢琴全集",
        "city": "上海市",
        "venue": "凯迪拉克·上海音乐厅-大厅",
        "time": "2026.06.13 周六 19:00",
        "price_min": 80,
        "price_max": 580,
        "link": "https://detail.damai.cn/item.htm?id=1041010456246",
        "tracks": [
            "《怪诞小夜曲》",
            "《古典小步舞曲》",
            "《悼念公主的帕凡舞曲》",
            "《水之嬉戏》",
            "《小奏鸣曲》",
            "《镜》",
            "《以海顿之名的小步舞曲》",
            "《高贵而伤感的圆舞曲》",
            "《夜之幽灵》",
            "《鲍罗丁风格》",
            "《夏布里埃风格》",
            "《前奏曲》",
            "《库普兰之墓》"
        ]
    },
    {
        "id": "1019577270067",
        "name": "【上海】【奇妙嘿夜】烛光音乐会“爱乐之城”主题世界影视曲目沉浸式演出钢琴&小提琴&大提琴演奏",
        "city": "上海市",
        "venue": "八号桥艺术空间——1908粮仓",
        "time": "2026.06.06-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=1019577270067",
        "tracks": [
            "LaLaLand",
            "圣母颂，劳伦斯先生",
            "天空之城",
            "你的名字",
            "自由探索",
            "人类的赞美马",
            "随它吧 (Let It Go)",
            "我心永恒",
            "暗香",
            "Young and Beautiful",
            "一步之遥",
            "A Thousand Years",
            "自由探戈",
            "He's a Pirate"
        ]
    },
    {
        "id": "1036493880465",
        "name": "【上海】【限时5折】2026上海儿童亲子音乐会",
        "city": "上海市",
        "venue": "虹桥艺术中心",
        "time": "2026.06.07 周日 10:30",
        "price_min": 80,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1036493880465",
        "tracks": [
            "《世界的约定》",
            "《欢乐颂》",
            "《红猪组曲》",
            "《西班牙斗牛士》",
            "《龙猫组曲》",
            "《四小天鹅》",
            "《千与千寻》",
            "《天鹅湖》",
            "《悬崖上的金鱼公主》",
            "《友谊地久天长》",
            "《前前世》",
            "《致爱丽丝》",
            "《肖斯塔科维奇第二圆舞曲》",
            "《天空之城》",
            "《菊次郎的夏天 + 孤勇者》"
        ]
    },
    {
        "id": "1046521610867",
        "name": "【上海】张雄关·关于爵士室内乐团 X 孙颖迪 X 刘泉君 专场音乐会",
        "city": "上海市",
        "venue": "久事·上海商城剧院",
        "time": "2026.06.05 周五 19:30",
        "price_min": 180,
        "price_max": 880,
        "link": "https://detail.damai.cn/item.htm?id=1046521610867",
        "tracks": []
    },
    {
        "id": "1052251788854",
        "name": "【上海】「探索音乐经典」——“世界音乐地图”系列音乐会 中国音乐专场之（二）",
        "city": "上海市",
        "venue": "九棵树未来艺术中心-小剧场",
        "time": "2026.05.31 周日 15:00",
        "price_min": 80,
        "price_max": 80,
        "link": "https://detail.damai.cn/item.htm?id=1052251788854",
        "tracks": [
            "春节序曲",
            "金蛇狂舞",
            "夜来香",
            "梁祝",
            "花好月圆",
            "步步高",
            "同一首歌",
            "猜调",
            "彩云追月",
            "卖汤圆",
            "绒花",
            "玛依拉",
            "北风吹",
            "相思河畔"
        ]
    },
    {
        "id": "1049644719844",
        "name": "【上海】「轻听九棵树」 ——《辉煌岁月》那些年我们一起追过的港台金曲音乐会",
        "city": "上海市",
        "venue": "九棵树未来艺术中心-小剧场",
        "time": "2026.06.20 周六 15:00",
        "price_min": 80,
        "price_max": 120,
        "link": "https://detail.damai.cn/item.htm?id=1049644719844",
        "tracks": [
            "《勇气》",
            "《爱就一个字》",
            "《有多少爱可以重来》",
            "《后来》",
            "《在我生命中的每一天》",
            "《光阴的故事》",
            "《爱如潮水》",
            "《爱你》",
            "《找自己》",
            "《月半小夜曲》",
            "《红日》",
            "《心动》",
            "《千千阙歌》",
            "《祝福》",
            "《日不落》",
            "《真情人》",
            "《海阔天空》",
            "《失恋阵线联盟》",
            "《情非得已》",
            "《女人花》",
            "《潇洒走一回》",
            "《当爱已成往事》",
            "《铁血丹心+世间始终你好》",
            "《明天会更好》"
        ]
    },
    {
        "id": "1019576758391",
        "name": "【上海】奇妙嘿夜烛光音乐会久石让&宫崎骏“天空之城”曲目沉浸式演奏钢琴&小提琴&大提琴",
        "city": "上海市",
        "venue": "青春无限音乐厅-上海广场店",
        "time": "2026.06.06-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=1019576758391",
        "tracks": [
            "Merry Christmas Mr. Lawrence",
            "Merry-Go-Round of Life",
            "Rain",
            "Totoro",
            "Summer",
            "One Summer's Day",
            "Ponyo on the Cliff",
            "The Legend of Ashitaka",
            "A Town With an Ocean View",
            "The Wind Rises",
            "Castle in the Sky"
        ]
    },
    {
        "id": "1044371971434",
        "name": "【上海】《侠骨柔情》经典武侠影视金曲音乐会",
        "city": "上海市",
        "venue": "上海长滩音乐厅",
        "time": "2026.06.13 周六 19:00",
        "price_min": 99,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1044371971434",
        "tracks": [
            "铁血丹心",
            "万里长城永不倒",
            "英雄谁属",
            "笑傲江湖",
            "倩女幽魂",
            "刀剑如梦",
            "难忘的经",
            "烟雨江南",
            "红豆词",
            "岁月悠悠",
            "追梦人"
        ]
    },
    {
        "id": "1030687411437",
        "name": "【上海】上海爱乐乐团2025-2026音乐季 乐游地球系列 探索俄罗斯之二",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.26 周五 19:30",
        "price_min": 50,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1030687411437",
        "tracks": [
            "谢尔盖·拉赫玛尼诺夫：D小调第三钢琴协奏曲，作品30",
            "亚历山大·尼古拉耶维奇·斯科里亚宾：C小调第三交响曲“神圣之诗”，作品43"
        ]
    },
    {
        "id": "1037338899362",
        "name": "【上海】诗与歌 – 无伴奏合唱专场音乐会",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.06 周六 19:30",
        "price_min": 180,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1037338899362",
        "tracks": [
            "四首莎士比亚歌曲（1984）",
            "降临吧，死亡",
            "摇篮曲",
            "劳苦加倍，烦恼成双",
            "水下五英寻",
            "三首莎士比亚歌曲（1951）",
            "水下五英寻",
            "云中高塔",
            "越过山丘，越过溪谷",
            "英勇的纺织工（1997）",
            "五首花之歌，第47号（1950）",
            "No.4 月见草",
            "No.5 绿金雀花谣",
            "八首合唱曲，第119号（1910）",
            "No.3 蓝鸟",
            "放下花环（1840）",
            "《吕克特之歌》之五，我已与世隔绝（1901-1902）",
            "《旅人之歌》之四，蓝色双眸（1884-1885）",
            "奥尔良公爵的三首香颂，L.99（92）（1898-1908）",
            "1、天啊！她如此百看不厌",
            "2、当铃鼓声响起",
            "3、冬天，你就是个坏蛋",
            "小柔板，选自《第五交响曲》第四乐章（1901-1902）"
        ]
    },
    {
        "id": "1048712276460",
        "name": "【上海】著名女中音歌唱家乔伊斯·迪多纳托演绎《点唱机》音乐会",
        "city": "上海市",
        "venue": "凯迪拉克·上海音乐厅-大厅",
        "time": "2026.06.04 周四 19:30",
        "price_min": 180,
        "price_max": 680,
        "link": "https://detail.damai.cn/item.htm?id=1048712276460",
        "tracks": []
    },
    {
        "id": "1005329031624",
        "name": "【上海】【奇妙嘿夜】久石让&宫崎骏&坂本龙一曲目“天空之城”主题烛光音乐会",
        "city": "上海市",
        "venue": "八号桥艺术空间——1908粮仓",
        "time": "2026.06.05-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=1005329031624",
        "tracks": [
            "Merry Christmas Mr. Lawrence",
            "Merry-Go-Round of Life",
            "Rain",
            "Totoro",
            "Summer",
            "One Summer's Day",
            "Always With Me",
            "Ponyo on the Cliff",
            "The legend of Ashitaka",
            "A Town With an Ocean View",
            "The Wind Rises",
            "Castle in the Sky"
        ]
    },
    {
        "id": "1046428493492",
        "name": "【上海】“大师风采”系列《阎惠昌与上海民族乐团》",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.14 周日 19:30",
        "price_min": 80,
        "price_max": 580,
        "link": "https://detail.damai.cn/item.htm?id=1046428493492",
        "tracks": [
            "民族管弦乐《八音和鸣》",
            "二胡协奏曲《长城随想曲》（引子加三四乐章）",
            "唢呐协奏曲《百年瑰梦》（民乐版首演）",
            "民族管弦乐《幻想曲:秦·兵马俑》"
        ]
    },
    {
        "id": "1036962135974",
        "name": "【上海】《童年的纸飞机》专场音乐会",
        "city": "上海市",
        "venue": "保利上海城市剧院",
        "time": "2026.06.20 周六 19:30",
        "price_min": 80,
        "price_max": 580,
        "link": "https://detail.damai.cn/item.htm?id=1036962135974",
        "tracks": [
            "1.《定风波·莫听穿林打叶声》",
            "2.《山中月》",
            "3.《后会无期》",
            "4.《菊花台》",
            "5.《雪落下的声音》",
            "6.《蜗牛》",
            "7.《大鱼》",
            "8.《落叶归根》",
            "9.《爱》",
            "10.《新不了情》",
            "11.《老鼠爱大米》",
            "12.《铁血丹心》",
            "13.《邓丽君组歌》",
            "14.《失恋阵线联盟》"
        ]
    },
    {
        "id": "1033278298931",
        "name": "【上海】大师公益系列 玛尔科 • 塔玛约古典吉他独奏音乐会",
        "city": "上海市",
        "venue": "凯迪拉克·上海音乐厅-大厅",
        "time": "2026.06.07 周日 19:30",
        "price_min": 80,
        "price_max": 120,
        "link": "https://detail.damai.cn/item.htm?id=1033278298931",
        "tracks": [
            "前奏曲、赋格曲与快板 BWV 998——J. S. 巴赫（编曲：Marco Tamayo）",
            "大独奏曲 Op. 14——F. 索尔",
            "《吟游诗人之歌》——J. K. 梅尔茨",
            "《致远方的人》An die Entfernte",
            "《诙谐曲》Scherzo",
            "《随想曲》作品1中第13、17和24首（改编：Marco Tamayo）— N. 帕格尼尼",
            "中场休息",
            "《感伤华尔兹》Op. 51 第6号——P. I. 柴科夫斯基（改编：Marco Tamayo）",
            "华尔兹 Op. 8第4号——A. B. 曼戈雷",
            "《热情马祖卡》——A. B. 曼戈雷",
            "《大教堂》——A. B. 曼戈雷",
            "《威尼斯狂欢节主题与变奏》——F. 塔雷加"
        ]
    },
    {
        "id": "1024758822602",
        "name": "【上海】一个人的古典——内心的风景 ·王文升钢琴独奏音乐会",
        "city": "上海市",
        "venue": "上海大剧院-中剧场",
        "time": "2026.06.14 周日 19:30",
        "price_min": 100,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1024758822602",
        "tracks": [
            "约翰内斯·勃拉姆斯 舒曼主题变奏曲，作品9",
            "约瑟夫·海顿 E 大调庄严的广板，出自海顿《G小调“骑士”弦乐四重奏》第二乐章，Hob. III:74/II",
            "约瑟夫·海顿 E 大调键盘奏鸣曲，Hob. XVI:31",
            "贝拉·巴托克 三首练习曲，作品 18",
            "费利克斯·门德尔松 无词歌，作品102",
            "谢尔盖·普罗科菲耶夫 降 B 大调第八钢琴奏鸣曲，作品 84"
        ]
    },
    {
        "id": "1052052564607",
        "name": "【上海】《听见俄罗斯》交响音乐会（公益场）",
        "city": "上海市",
        "venue": "临港演艺中心",
        "time": "2026.06.13 周六 14:30",
        "price_min": 80,
        "price_max": 80,
        "link": "https://detail.damai.cn/item.htm?id=1052052564607",
        "tracks": [
            "Variations of the theme by Tchaikovsky",
            "String Quartet No.8, op.110",
            "Souvenir de Florence in d minor, Op. 70, TH 118"
        ]
    },
    {
        "id": "1020698265162",
        "name": "【上海】超越奏鸣曲--张昊辰钢琴独奏音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.18 周四 19:30",
        "price_min": 180,
        "price_max": 880,
        "link": "https://detail.damai.cn/item.htm?id=1020698265162",
        "tracks": [
            "贝多芬 | A大调第二十八钢琴奏鸣曲，作品101",
            "舒曼 | 升F小调第一钢琴奏鸣曲，作品11",
            "贝多芬 | 降A大调第三十一钢琴奏鸣曲，作品110",
            "舒曼 | C大调幻想曲，作品17",
            "Beethoven | Piano Sonata No. 28 in A Major, Op. 101",
            "Schumann | Piano Sonata No. 1 in F-Sharp Minor, Op. 11",
            "Beethoven | Piano Sonata No. 31 in A-Flat Major, Op. 110",
            "Schumann | Fantasy in C Major, Op. 17"
        ]
    },
    {
        "id": "1040979618197",
        "name": "【上海】与你同乐·钢琴的传奇之旅音乐会 ——肖邦第五代直系传承钢琴家迈克·彼亚克2026上海站",
        "city": "上海市",
        "venue": "九棵树未来艺术中心-大剧场",
        "time": "2026.06.21 周日 14:30",
        "price_min": 80,
        "price_max": 580,
        "link": "https://detail.damai.cn/item.htm?id=1040979618197",
        "tracks": [
            "Beethoven - Moonlight Sonata 1st Movement",
            "Mozart - Fantasy d minor K.397",
            "Falla - Danza Ritual del Fuego",
            "黄虎威 - 阳光灿烂照天山",
            "Chopin - Polonaise Op. 26 No.1",
            "Chopin - Valse Op.34 No. 2",
            "Debussy - Rhapsody",
            "Chopin - Nocturne Op. 9 No. 1",
            "Chopin - Etude Op. 10 No. 1",
            "Chopin - Mazurka Op. 6 No.2",
            "Chopin - Nocturne Op. 15. No. 1"
        ]
    },
    {
        "id": "1045463534720",
        "name": "【上海】经典荟萃-漫步音乐三百年 萨克斯的古典新编与声音奇想——阿拉四重奏音乐会",
        "city": "上海市",
        "venue": "上海保利大剧院-小剧场",
        "time": "2026.06.14 周日 14:00",
        "price_min": 30,
        "price_max": 30,
        "link": "https://detail.damai.cn/item.htm?id=1045463534720",
        "tracks": [
            "比才 卡门幻想曲",
            "Bizet Carmen Fantasy, arr. Ito",
            "圣桑 骷髅之舞",
            "Saint-Saëns Danse Macabre, arr. Yamada",
            "圣桑 酒神之舞",
            "Saint-Saëns Bacchanale, arr. Yamada",
            "伊图拉尔德 小查尔达什舞曲",
            "Iturralde Pequeña Czardas",
            "江苏民歌 茉莉花",
            "Traditional Jasmine Flower, arr. Sho Oie",
            "中场休息",
            "Intermission",
            "派克 极端措施",
            "Peck Drastic Measures",
            "吉松隆 原子核俱乐部",
            "Yoshimatsu Atom Heart Club Quartet",
            "I. 快板",
            "II. 行板",
            "III. 谐谑曲",
            "IV. 终曲",
            "村松崇继 生命的奇迹",
            "Muramatsu Song of life, arr. Asari",
            "八木泽教司 阳炎之舞",
            "Yagisawa Dance in the Heat Haze",
            "葉加濑太郎 情热大陆",
            "Hakase Jounetsu-Tairiku, arr. Asari"
        ]
    },
    {
        "id": "1012490108257",
        "name": "【上海】奇妙嘿夜烛光音乐会“爱乐之城主题”世界影视作品曲目LALALAND钢琴&小提琴&大提琴演奏",
        "city": "上海市",
        "venue": "青春无限音乐厅-上海广场店",
        "time": "2026.06.06-06.19",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=1012490108257",
        "tracks": [
            "LaLaLand",
            "圣圣诞乐，劳伦斯先生",
            "天空之城",
            "三叶",
            "自由探戈",
            "Mystery Of Love",
            "生命万岁",
            "我心永恒",
            "白色巨塔",
            "Young and Beautiful",
            "一步一步之遥",
            "美女与野兽",
            "He's a Pirate",
            "星际穿越"
        ]
    },
    {
        "id": "1043652245057",
        "name": "【上海】风雷万象—— 2026中国青年作曲家电子×民乐多媒体跨界狂想音乐会",
        "city": "上海市",
        "venue": "久事·上海商城剧院",
        "time": "2026.06.03 周三 19:30",
        "price_min": 50,
        "price_max": 180,
        "link": "https://detail.damai.cn/item.htm?id=1043652245057",
        "tracks": [
            "风雷腾渊",
            "止于照见",
            "冰下磁极",
            "未·末",
            "朝闻道",
            "枫桥夜泊",
            "兵法II:九衍",
            "不古",
            "行·意",
            "籁·境"
        ]
    },
    {
        "id": "1042310000024",
        "name": "【上海】上海爱乐乐团2025-2026音乐季 走近爱乐·室内乐系列 中西和鸣",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-演艺厅",
        "time": "2026.06.12 周五 19:15",
        "price_min": 50,
        "price_max": 280,
        "link": "https://detail.damai.cn/item.htm?id=1042310000024",
        "tracks": [
            "鲍元恺：《炎黄风情》选段",
            "(1) 猜调",
            "(2) 走西口",
            "(3) 杨柳青",
            "(4) 女娃担水-主题变奏曲",
            "李四光：弦乐四重奏《行路难》（改编：刘灏）",
            "吕其明：管子独奏《缅怀》",
            "刘泽锴：《赤鸿》，为二胡和弦乐队而作",
            "爱德华·埃尔加：E小调小夜曲，作品20",
            "乔治·弗里德里希·亨德尔：C小调大协奏曲，作品6之第8首"
        ]
    },
    {
        "id": "1017709802593",
        "name": "【上海】【奇妙嘿夜】钢琴&古筝国风专场烛光音乐会梦互联动“霍元甲”“曹操”等曲目演奏沉浸式演出",
        "city": "上海市",
        "venue": "青春无限音乐厅-上海广场店",
        "time": "2026.05.31-06.14",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=1017709802593",
        "tracks": [
            "不染",
            "如愿",
            "苏幕遮",
            "青花瓷",
            "兰亭序",
            "起风了",
            "云水谣",
            "知否知否",
            "天若有情",
            "雪落下的声音"
        ]
    },
    {
        "id": "1024913486070",
        "name": "【上海】《谁与“筝”锋——古筝三重奏音乐会》",
        "city": "上海市",
        "venue": "上海天蟾逸夫舞台蟾空间",
        "time": "2026.05.31 周日 14:30",
        "price_min": 150,
        "price_max": 150,
        "link": "https://detail.damai.cn/item.htm?id=1024913486070",
        "tracks": [
            "盛世国乐",
            "蝴蝶泉边",
            "璃月",
            "小星星",
            "云宫迅音",
            "蝴蝶与蓝",
            "大鱼",
            "兰亭序",
            "踏雪归集",
            "青花瓷",
            "赤焰之缨",
            "勇气大爆发",
            "孤勇者",
            "刀剑如梦",
            "离别开出花"
        ]
    },
    {
        "id": "1042016423286",
        "name": "【上海】古典音乐会《爱搬家的贝多芬》",
        "city": "上海市",
        "venue": "上海文化广场-音乐剧中心A空间",
        "time": "2026.05.31 周日 16:00",
        "price_min": 240,
        "price_max": 240,
        "link": "https://detail.damai.cn/item.htm?id=1042016423286",
        "tracks": []
    },
    {
        "id": "1052807011657",
        "name": "【上海】[怀旧经典]《海上花》室内音乐会|重返上海滩",
        "city": "上海市",
        "venue": "SKY天美影剧院-OD第一剧场",
        "time": "2026.06.05 周五 20:00",
        "price_min": 88,
        "price_max": 128,
        "link": "https://detail.damai.cn/item.htm?id=1052807011657",
        "tracks": [
            "夜上海",
            "暗香",
            "城里的月光",
            "繁花",
            "月亮代表我的心"
        ]
    },
    {
        "id": "1056269608216",
        "name": "【上海】“拾”光为壤，声声不凡 上海音乐学院阿卡贝拉社团十周年专场音乐会",
        "city": "上海市",
        "venue": "贺绿汀音乐厅",
        "time": "2026.06.12 周五 19:30",
        "price_min": 30,
        "price_max": 180,
        "link": "https://detail.damai.cn/item.htm?id=1056269608216",
        "tracks": [
            "A Cappella",
            "二十二岁的月亮",
            "Words",
            "Lydía",
            "一荤一素",
            "D小调双小提琴协奏曲 (BWV 1043) 第一乐章",
            "One World Rhythm",
            "重生之我在五号楼门口当小猫",
            "Butterfly",
            "小河淌水",
            "This is me",
            "又是艳阳天",
            "红绣花",
            "Sorry Seems To Be The Hardest Word",
            "灯火里的中国",
            "Like Jennie",
            "Ice Cream Dynamite",
            "All I Ask Of You",
            "九儿",
            "维吾尔族民歌《亚里亚》",
            "Waltz For Debby",
            "The High Moon",
            "有我"
        ]
    },
    {
        "id": "1044609191943",
        "name": "【上海】坂本龙一・星空烛光经典音乐会",
        "city": "上海市",
        "venue": "YOUNG剧场·主剧场",
        "time": "2026.06.27 周六 19:30",
        "price_min": 68,
        "price_max": 208,
        "link": "https://detail.damai.cn/item.htm?id=1044609191943",
        "tracks": [
            "1.遮蔽的天空--《遮蔽的天空》",
            "2.Aqua--《怪物》",
            "3.Energy Flow--坂本龙一独奏专辑《BTTB》",
            "4.summer--《菊次郎的夏天》",
            "5.末代皇帝--《末代皇帝》",
            "6.雨--《末代皇帝》",
            "7.千与千寻-那个夏天--《千与千寻》",
            "8.千与千寻-永远同在--《千与千寻》",
            "9.世界的约定--《哈尔的移动城堡》",
            "10.人生的旋转木马--《哈尔的移动城堡》",
            "11天空之城--《天空之城》",
            "12.幽灵公主--《幽灵公主》",
            "13.能看见海的街道--《魔女宅急便》",
            "14.Memory--《入殓师》(钢琴, 大提琴)",
            "15.悬崖上的金鱼姬--《悬崖上的金鱼姬》",
            "16.圣诞快乐, 劳伦斯先生--《圣诞快乐, 劳伦斯先生》"
        ]
    },
    {
        "id": "1014633482775",
        "name": "【上海】流浪者三重奏演绎肖斯塔科维奇丨上海交响乐团音乐季",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-演艺厅",
        "time": "2026.06.13 周六 19:15",
        "price_min": 80,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1014633482775",
        "tracks": [
            "肖斯塔科维奇：c小调第一钢琴三重奏，作品8",
            "肖斯塔科维奇：e小调第二钢琴三重奏，作品67",
            "肖斯塔科维奇：g小调钢琴五重奏，作品57"
        ]
    },
    {
        "id": "1005147442792",
        "name": "【上海】【奇妙嘿夜】世界影视作品“LaLaLand”曲目钢琴小提琴大提琴演奏烛光音乐会百年历史建筑主题",
        "city": "上海市",
        "venue": "八号桥艺术空间——1908粮仓",
        "time": "2026.06.06-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=1005147442792",
        "tracks": [
            "LaLaLand",
            "圣母颂，劳伦斯先生",
            "天空之城",
            "你的名字",
            "自由探索",
            "人类的赞美马",
            "随它吧 (Let It Go)",
            "我心永恒",
            "暗香",
            "Young and Beautiful",
            "一步之遥",
            "A Thousand Years",
            "自由探戈",
            "He's a Pirate"
        ]
    },
    {
        "id": "1049698081896",
        "name": "【上海】咏叹与乡韵——中外声乐作品夏夜音乐会",
        "city": "上海市",
        "venue": "云峰剧院",
        "time": "2026.06.26 周五 19:15",
        "price_min": 56,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1049698081896",
        "tracks": []
    },
    {
        "id": "1039827424677",
        "name": "【上海】【6月20日】Syncopated moon light·潮汐神经元——波频·链接·肢体",
        "city": "上海市",
        "venue": "光新无限演艺中心",
        "time": "2026.06.20 周六 19:30",
        "price_min": 118,
        "price_max": 125,
        "link": "https://detail.damai.cn/item.htm?id=1039827424677",
        "tracks": []
    },
    {
        "id": "1052279586414",
        "name": "【上海】上海国青管弦乐团2026夏日音乐会",
        "city": "上海市",
        "venue": "上音歌剧院·歌剧厅",
        "time": "2026.06.21 周日 19:30",
        "price_min": 80,
        "price_max": 580,
        "link": "https://detail.damai.cn/item.htm?id=1052279586414",
        "tracks": [
            "卡门组曲",
            "一杯美酒",
            "我火热的双唇",
            "芝加哥Chicago",
            "魔法坏女巫Wicked",
            "小美人鱼The Little Mermaid",
            "好兆头主题曲",
            "神秘博士主题曲",
            "神探夏洛克主题曲"
        ]
    },
    {
        "id": "994986811185",
        "name": "【上海】2026东方市民音乐会：上海城市交响乐团音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.20 周六 10:00",
        "price_min": 80,
        "price_max": 80,
        "link": "https://detail.damai.cn/item.htm?id=994986811185",
        "tracks": [
            "莫扎特 | 歌剧《魔笛》序曲",
            "李斯特 | A大调第二号钢琴协奏曲，作品125",
            "莫扎特 | C大调第四十一交响曲，作品551"
        ]
    },
    {
        "id": "939280485307",
        "name": "【上海】【奇妙嘿夜】久石让&宫崎骏烛光音乐会“权力的游戏”主题三重奏钢琴&小提琴&大提琴",
        "city": "上海市",
        "venue": "青春无限音乐厅-上海广场店",
        "time": "2026.06.06-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=939280485307",
        "tracks": [
            "Merry Christmas Mr. Lawrence",
            "Merry-Go-Round of Life",
            "Rain",
            "Totoro",
            "Summer",
            "One Summer's Day",
            "Always With Me",
            "Ponyo on the Cliff",
            "The Legend of Ashitaka",
            "A Town With an Ocean View",
            "The Wind Rises",
            "Castle in the Sky",
            "La La Land",
            "Pearl Harbor",
            "Young and Beautiful",
            "Step One",
            "Starlight Express",
            "He's a Pirate",
            "Viva La Vida"
        ]
    },
    {
        "id": "1051009379232",
        "name": "【上海】李坚钢琴独奏音乐会",
        "city": "上海市",
        "venue": "不止空间(原新天安堂)",
        "time": "2026.06.20 周六 20:00",
        "price_min": 280,
        "price_max": 480,
        "link": "https://detail.damai.cn/item.htm?id=1051009379232",
        "tracks": [
            "门德尔松",
            "E大调无词歌，Op. 67 No. 1",
            "升F小调无词歌，Op. 67 No. 2",
            "g小调无词歌，Op. 19 No. 6",
            "A大调无词歌，Op. 62 No. 6",
            "C大调无词歌，Op. 67 No. 4",
            "贝多芬",
            "降A大调奏鸣曲，Op. 110",
            "钢琴奏鸣曲在A-flat Major, Op. 110",
            "罗伯特·舒曼",
            "大卫同盟舞曲，Op. 6"
        ]
    },
    {
        "id": "1008555839368",
        "name": "【上海】上交室内乐 7：克洛德·博兰小提琴、长笛与爵士钢琴三重奏丨上海交响乐团音乐季",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-演艺厅",
        "time": "2026.06.26 周五 19:15",
        "price_min": 120,
        "price_max": 120,
        "link": "https://detail.damai.cn/item.htm?id=1008555839368",
        "tracks": [
            "克洛德·博兰：小提琴与爵士钢琴三重奏组曲",
            "克洛德·博兰：长笛与爵士钢琴三重奏组曲"
        ]
    },
    {
        "id": "995584330178",
        "name": "【上海】2026东方市民音乐会： 世界民歌集——利盖蒂弦乐四重奏音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.06 周六 10:00",
        "price_min": 50,
        "price_max": 80,
        "link": "https://detail.damai.cn/item.htm?id=995584330178",
        "tracks": [
            "黄海怀 | 赛马（克里斯蒂安·梅森改编）",
            "福德·拉萨纳·迪亚巴特 | 娜娜・特里班，选自《桑贾塔时代》",
            "吴蛮 | 戈壁落日（丹尼·克莱改编）",
            "克里斯蒂安·梅森 | 撒丁岛歌集",
            "克里斯蒂安·梅森 | 图瓦歌集",
            "塔尼亚·塔加克 | 西武尼提尼",
            "利盖蒂 | 第一弦乐四重奏“夜的蜕变”",
            "加布里埃尔·威廉姆斯 | 星际密码",
            "阿雅娜·威特-约翰逊 | 曼托心情",
            "J.A. 安德森 | 多罗泰亚的波兰舞曲（丹麦弦乐四重奏团改编）",
            "娄·哈里森 | 中世纪舞曲"
        ]
    },
    {
        "id": "1021353698436",
        "name": "【上海】一个人的古典——双弦纪 蒋文瀚中提琴与肩式大提琴无伴奏音乐会",
        "city": "上海市",
        "venue": "上海大剧院-中剧场",
        "time": "2026.06.30 周二 19:30",
        "price_min": 100,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1021353698436",
        "tracks": [
            "弗雷德里希·赫尔曼：前奏曲与小赋格，选自《音乐会练习曲》，作品18",
            "捷尔吉·利盖蒂：环，选自《无伴奏中提琴奏鸣曲》",
            "捷尔吉·库塔克：《符号、游戏与讯息》选曲",
            "捷尔吉·利盖蒂：哀歌，选自《无伴奏中提琴奏鸣曲》",
            "J·S·巴赫：恰空，选自《无伴奏小提琴第二帕蒂塔》，作品1004",
            "本杰明·布里顿：帕萨卡利亚，选自《第三无伴奏大提琴组曲》作品87",
            "J·S·巴赫：第六无伴奏大提琴组曲，作品1012"
        ]
    },
    {
        "id": "1054484037251",
        "name": "【上海】《二十四琴歌沉浸式音乐会•芒种篇》",
        "city": "上海市",
        "venue": "檐也二十四集",
        "time": "2026.06.06 周六 19:00",
        "price_min": 198,
        "price_max": 198,
        "link": "https://detail.damai.cn/item.htm?id=1054484037251",
        "tracks": [
            "芒种",
            "欢沁",
            "无羁"
        ]
    },
    {
        "id": "1001481929395",
        "name": "【上海】【百联西郊】沉浸式古琴疗愈体验《黑暗听古琴》",
        "city": "上海市",
        "venue": "飞来飞去的棉花糖99号·九坛酒戏剧艺术空间",
        "time": "2026.06.06-09.19",
        "price_min": 120,
        "price_max": 200,
        "link": "https://detail.damai.cn/item.htm?id=1001481929395",
        "tracks": [
            "《无》",
            "《无尘》",
            "《良宵引》",
            "《神人畅》",
            "《平沙落雁》",
            "《春》",
            "《普安咒》",
            "《洞庭秋思》",
            "《弦音枕流》",
            "《鸥鹭忘机》",
            "《送别》"
        ]
    },
    {
        "id": "911571762419",
        "name": "【上海】【奇妙嘿夜】“爱乐之城”--世界影视作品曲目烛光音乐会钢琴&小提琴&大提琴演出",
        "city": "上海市",
        "venue": "八号桥艺术空间——1908粮仓",
        "time": "2026.06.06-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=911571762419",
        "tracks": [
            "LaLaLand",
            "圣母颂，劳伦斯先生",
            "天空之城",
            "你的名字",
            "自由探索",
            "人类的赞美马",
            "随它吧 (Let It Go)",
            "我心永恒",
            "暗香",
            "Young and Beautiful",
            "一步之遥",
            "A Thousand Years",
            "自由探戈",
            "He's a Pirate"
        ]
    },
    {
        "id": "1044379727077",
        "name": "【上海】中国四大名著作品视听音乐会",
        "city": "上海市",
        "venue": "上海长滩音乐厅",
        "time": "2026.06.27 周六 19:00",
        "price_min": 99,
        "price_max": 360,
        "link": "https://detail.damai.cn/item.htm?id=1044379727077",
        "tracks": [
            "《水浒传》1998年版 主题曲《好汉歌》（演唱）",
            "《水浒传》1998年版 片尾曲《天时地利人和》",
            "《水浒传》1982年版 片头曲《一枝花》",
            "《三国演义》1994年版 片头曲《滚滚长江东逝水》",
            "《三国演义》1994年版 片尾曲《历史的天空》（演唱）",
            "《西游记》1986年版 片头曲《云宫迅音》",
            "《西游记》1986年版 片尾曲《敢问路在何方》（演唱）",
            "《西游记》1986年版 插曲《大圣歌》",
            "《西游记》1986年版 插曲《猪八戒之歌》",
            "《西游记》1986年版 插曲《女儿情》（演唱）",
            "《西游记》2000年版 片头曲《通天大道宽又阔》",
            "《红楼梦》1987年版 序曲《红楼梦序曲》",
            "《红楼梦》1987年版 插曲《红豆曲》（演唱）",
            "《红楼梦》1987年版 插曲《葬花吟》",
            "《红楼梦》1987年版 插曲《题帕三绝》",
            "《红楼梦》1987年版 插曲《秋窗风雨夕》",
            "《红楼梦》1987年版 插曲《晴雯歌》（演唱）",
            "《红楼梦》1987年版 插曲《紫菱洲歌》",
            "《红楼梦》1987年版 插曲《叹香菱》",
            "《红楼梦》1987年版 插曲《聪明累》",
            "《红楼梦》1987年版 主题曲《枉凝眉》（演唱）"
        ]
    },
    {
        "id": "1032114516559",
        "name": "【上海】“我和我的祖国”红色经典电影插曲音乐会",
        "city": "上海市",
        "venue": "上海天蟾逸夫舞台蟾空间",
        "time": "2026.06.27 周六 19:30",
        "price_min": 150,
        "price_max": 150,
        "link": "https://detail.damai.cn/item.htm?id=1032114516559",
        "tracks": [
            "娘子军连歌",
            "红星歌",
            "北风吹",
            "弹起我心爱的土琵琶",
            "地道战",
            "追寻",
            "我的祖国",
            "英雄赞歌",
            "唱支山歌给党听",
            "歌唱祖国",
            "我和我的祖国"
        ]
    },
    {
        "id": "993538026341",
        "name": "【上海】《丝路之乐·唐韵回响》",
        "city": "上海市",
        "venue": "长江剧场-黑匣子",
        "time": "2026.06.12 周五 19:30",
        "price_min": 218,
        "price_max": 318,
        "link": "https://detail.damai.cn/item.htm?id=993538026341",
        "tracks": [
            "碣石调·幽兰",
            "急胡相问",
            "伊州",
            "水鼓子",
            "急曲子·I",
            "长沙女引",
            "急曲子·II",
            "又慢曲子·西江月",
            "急曲子·III",
            "倾杯乐",
            "石上流泉"
        ]
    },
    {
        "id": "940180472926",
        "name": "【上海】【奇妙嘿夜】烛光音乐会“海上钢琴师”“爱乐之城”“加勒比海盗”曲目钢琴&小提琴",
        "city": "上海市",
        "venue": "青春无限音乐厅-上海广场店",
        "time": "2026.05.31-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=940180472926",
        "tracks": [
            "诀别诗",
            "流苏",
            "加勒比海盗",
            "星空下的梦想",
            "帐号已注销",
            "致爱丽丝",
            "世界赠予我的",
            "克罗地亚狂想曲",
            "爱的礼赞",
            "神话",
            "天气之子",
            "月半小夜曲",
            "权利的游戏",
            "花之舞"
        ]
    },
    {
        "id": "1048315063500",
        "name": "【上海】20260619“琴韵流金，福爱永随”朱璟廷钢琴独奏音乐会",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-演艺厅",
        "time": "2026.06.19 周五 19:15",
        "price_min": 80,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1048315063500",
        "tracks": [
            "拉威尔：庆典，M. 11",
            "贝多芬：E小调第27号钢琴奏鸣曲，作品90",
            "斯克里亚宾：8首练习曲，作品42",
            "肖邦：幻想曲，作品49",
            "肖邦：幻想波兰舞曲，作品61",
            "肖邦：B小调第3号钢琴奏鸣曲，作品58"
        ]
    },
    {
        "id": "1052252084982",
        "name": "【上海】「百人百场未来大师」系列—— “听觉的棱镜”刘弦、郭子凌小提琴二重奏专场音乐会",
        "city": "上海市",
        "venue": "九棵树未来艺术中心-小剧场",
        "time": "2026.06.06 周六 15:00",
        "price_min": 80,
        "price_max": 80,
        "link": "https://detail.damai.cn/item.htm?id=1052252084982",
        "tracks": [
            "莫扎特12首为两把小提琴而作的二重奏，作品70",
            "改编：奥古斯特·舒尔茨 August Schulz",
            "第四首 改编自C大调钢琴与小提琴奏鸣曲K.296",
            "Sonata for piano and violin in C major, K.296",
            "第九首 改编自C大调钢琴三重奏 k.548",
            "Piano Trio in C major, k.548",
            "贝拉·巴托克44首双小提琴二重奏, Sz 98",
            "Béla Bartók - 44 Duets for two violins, Sz 98",
            "Band I: 1. 2. 4. 9. 12. 16. 19. 21. 22. 23. 24",
            "Band II: 26. 29. 32. 35. 36. 42. 44",
            "第一首 改编自降B大调钢琴与小提琴奏鸣曲k.378",
            "Sonata for piano and violin in B-flat major, k.378"
        ]
    },
    {
        "id": "946122270316",
        "name": "【上海】余隆、丹尼尔·霍普与上海交响乐团 纪念本杰明·布里顿逝世50周年音乐会",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.12 周五 19:30",
        "price_min": 80,
        "price_max": 880,
        "link": "https://detail.damai.cn/item.htm?id=946122270316",
        "tracks": [
            "埃尔加：「第九变奏：宁录」，选自《谜语变奏曲》",
            "布里顿：安魂交响曲，作品20",
            "布里顿：d小调小提琴协奏曲，作品15"
        ]
    },
    {
        "id": "1043621357895",
        "name": "【上海】肖航辰小提琴独奏音乐会",
        "city": "上海市",
        "venue": "U12剧场",
        "time": "2026.06.13 周六 19:00",
        "price_min": 50,
        "price_max": 280,
        "link": "https://detail.damai.cn/item.htm?id=1043621357895",
        "tracks": [
            "骷髅之舞——夏尔·卡米尔·圣桑",
            "摇篮曲Op.16——加布里埃尔·福雷",
            "梦后Op.7, No.1——加布里埃尔·福雷",
            "西西里舞曲 Op.78——加布里埃尔·福雷",
            "沉思——朱尔·马斯涅",
            "月光——克洛德·德彪西",
            "哈巴涅拉形式的小品——莫里斯·拉威尔",
            "茨冈——莫里斯·拉威尔",
            "千年铁树开了花——阿克俭",
            "十面埋伏——杨宝智",
            "渔舟唱晚——黎国荃",
            "丰收渔歌——李自立"
        ]
    },
    {
        "id": "1050405010155",
        "name": "【上海】「百人百场未来大师」系列—— “当咖啡遇上音乐”橡心室内乐团专场音乐会",
        "city": "上海市",
        "venue": "九棵树未来艺术中心-小剧场",
        "time": "2026.06.28 周日 15:00",
        "price_min": 80,
        "price_max": 80,
        "link": "https://detail.damai.cn/item.htm?id=1050405010155",
        "tracks": [
            "Libertango（自由探戈）",
            "Après un rêve(梦后）",
            "Cafe Music（咖啡音乐）",
            "爱乐之城组曲（选自电影《爱乐之城》",
            "Sicilienne（西西里舞曲）",
            "Las Cuatro Estaciones Porteñas：Primavera Porteña & Verano Porteño（布宜诺斯艾利斯的四季：春、夏）",
            "梁祝小提琴协奏曲（选段）"
        ]
    },
    {
        "id": "946752433604",
        "name": "【上海】乔纳森·诺特、吴蛮与上海交响乐团 杜韵琵琶协奏曲中国首演",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-主厅",
        "time": "2026.06.05 周五 19:30",
        "price_min": 80,
        "price_max": 1280,
        "link": "https://detail.damai.cn/item.htm?id=946752433604",
        "tracks": [
            "韦伯：《奥伯龙》序曲，作品306",
            "杜韵：琵琶协奏曲《听书》（中国首演）",
            "舒曼：d小调第四交响曲，作品120"
        ]
    },
    {
        "id": "898099675029",
        "name": "【上海】【钢琴&古筝演奏】奇妙嘿夜烛光音乐会”苏幕遮““兰亭序”“青花瓷”曲目中西结合国风专场",
        "city": "上海市",
        "venue": "八号桥艺术空间——1908粮仓",
        "time": "2026.05.31-06.19",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=898099675029",
        "tracks": [
            "不朽",
            "如梦令",
            "苏幕遮",
            "青花瓷",
            "兰亭序",
            "起了",
            "红尘客栈",
            "玉珠帘",
            "古筝",
            "雪落下的声音"
        ]
    },
    {
        "id": "1004489227434",
        "name": "【上海】【玲珑国乐】红楼绮梦——江南丝竹音乐会",
        "city": "上海市",
        "venue": "凯迪拉克·上海音乐厅-音乐立方",
        "time": "2026.06.21 周日 14:00",
        "price_min": 180,
        "price_max": 180,
        "link": "https://detail.damai.cn/item.htm?id=1004489227434",
        "tracks": [
            "《太虚引》",
            "《枉凝眉》",
            "《迎仙客》",
            "《浮生若寄》",
            "《牡丹亭寻梦》",
            "《品茗观鱼》",
            "《灯月交辉》",
            "《水月镜花》",
            "《天上掉下个林妹妹》",
            "《金陵清梦》",
            "《葬花吟》",
            "《大观园》"
        ]
    },
    {
        "id": "1035649317478",
        "name": "【上海】海上雅乐·爵醒国乐跨界音乐现场",
        "city": "上海市",
        "venue": "东方艺术中心-演奏厅",
        "time": "2026.06.27 周六 19:45",
        "price_min": 80,
        "price_max": 320,
        "link": "https://detail.damai.cn/item.htm?id=1035649317478",
        "tracks": [
            "《春歌》江浙民歌",
            "《彩云追月》广东民歌",
            "《Quizas Quizas Quizas》",
            "《平沙落雁》",
            "《小河淌水》云南民歌",
            "《春之歌》贵州苗族民歌",
            "《鹧鸪飞》",
            "《白夜》",
            "《鸿雁》内蒙古乌拉特民歌",
            "《Strasbourg St.Denis》",
            "《阳光三叠》琴曲",
            "《好花红》贵州布依族山歌—国家非遗艺术"
        ]
    },
    {
        "id": "820351010040",
        "name": "【上海】【五一专场】奇妙嘿夜烛光音乐会权力的游戏&月半小夜曲&起风了曲目钢琴&小提琴&大提琴",
        "city": "上海市",
        "venue": "八号桥艺术空间——1908粮仓",
        "time": "2026.05.31-06.20",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=820351010040",
        "tracks": [
            "菊—《我的遗憾》",
            "秋意浓—《秋意浓》",
            "夜曲有爱天籁—《夜曲》",
            "如梦—《如梦》",
            "如歌—《如歌的行板》",
            "匆匆那年—《匆匆那年》",
            "这世界那么多人—《我要和你在一起》",
            "蒲公英的约定—《我怀念的》",
            "晴天—《对岸》",
            "青花瓷—《青花瓷》",
            "金玉良缘主题曲—《富士山下》",
            "起风了—《买不了的事》",
            "月半小夜曲—《命运号角》",
            "红玫瑰—《红玫瑰》",
            " WHAT'S GOING ON—《WHAT'S GOING ON》",
            "暖色—《暖色》",
            "彩虹—《彩虹》",
            "我怀念的—《我怀念的》",
            "我的七夕—《我的七夕》",
            "莫文蔚的作品—《莫文蔚的作品》",
            "最伟大的作品—《最伟大的作品》",
            "忘记记—《忘记记》",
            "江南—《江南》",
            "第二梦—《第二梦》",
            "她说—《她说》",
            "曾记得—《曾记得》",
            "背对背拥抱—《100天》",
            "少女时代—《GUGLY BEAUTY》"
        ]
    },
    {
        "id": "1010252515021",
        "name": "【上海】【钢琴&大提琴】奇妙嘿夜烛光音乐会权力的游戏&月半小夜曲&起风了曲目百年历史建筑演出",
        "city": "上海市",
        "venue": "八号桥艺术空间——1908粮仓",
        "time": "2026.06.05-06.26",
        "price_min": 98,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=1010252515021",
        "tracks": [
            "消失的她",
            "月半小夜曲",
            "命运符号",
            "雪落下的声音",
            "延禧攻略",
            "如愿",
            "我和我的父辈",
            "那些年",
            "点燃",
            "萱草花",
            "你好，李焕英",
            "我愿意",
            "晴天",
            "十万个为什么",
            "11月的萧邦",
            "七里香",
            "七里香",
            "她说",
            "光年之外",
            "青花瓷"
        ]
    },
    {
        "id": "1048942916762",
        "name": "【上海】《蝶舞·水云间》彩蝶女乐专场音乐会",
        "city": "上海市",
        "venue": "大零号湾文化艺术中心",
        "time": "2026.06.14 周日 19:30",
        "price_min": 60,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1048942916762",
        "tracks": [
            "开场 《钱塘畅想》",
            "一、《蝶舞》",
            "二、《水乡小唱》+《战马奔腾》",
            "三、《三六》江南丝竹",
            "四、《苏堤漫步》",
            "五、《酒狂》+《忆江南》",
            "六、《浪漫如烟》",
            "七、《咏南》",
            "八、《雁回》",
            "九、《山语幻》",
            "十、武侠金曲串烧",
            "十一、《梁祝》+《采茶舞曲》"
        ]
    },
    {
        "id": "840118240495",
        "name": "【上海】奇妙嘿夜烛光音乐会最伟大的作品曲目&百年历史建筑主题音乐会",
        "city": "上海市",
        "venue": "八号桥艺术空间——1908粮仓",
        "time": "2026.06.19 周五 20:20",
        "price_min": 388,
        "price_max": 388,
        "link": "https://detail.damai.cn/item.htm?id=840118240495",
        "tracks": [
            "江南 -《第二支香》",
            "曹轩宾 -《她》",
            "曾轶可 -《最天使》",
            "北村少年 -《UGLY BEAUTY》",
            "魏巍 -《魏巍》",
            "我的第七章 -《张灯结彩》",
            "莫文蔚 -《大丈夫》",
            "七堇年 -《七里香》"
        ]
    },
    {
        "id": "1032103540660",
        "name": "【上海】“花儿为什么这样红”红色经典电影插曲音乐会",
        "city": "上海市",
        "venue": "上海天蟾逸夫舞台蟾空间",
        "time": "2026.06.28 周日 14:30",
        "price_min": 150,
        "price_max": 150,
        "link": "https://detail.damai.cn/item.htm?id=1032103540660",
        "tracks": [
            "游击队之歌",
            "让我们荡起双浆",
            "草原之夜",
            "花儿为什么这样红",
            "红梅赞",
            "红星照我去战斗",
            "绣红旗",
            "雁南飞",
            "我们的生活充满阳光",
            "驼铃",
            "大海啊，故乡",
            "血染的风采"
        ]
    },
    {
        "id": "998518006759",
        "name": "【上海】《静待花开 SONGS OF LIGHT》烛光音乐会",
        "city": "上海市",
        "venue": "飞来飞去的棉花糖6号·STAGE1",
        "time": "2026.06.19 周五 19:30",
        "price_min": 98,
        "price_max": 455,
        "link": "https://detail.damai.cn/item.htm?id=998518006759",
        "tracks": [
            "BELIEVED (FROM \"THE POLAR EXPRESS\")",
            "CAULO LANG SYMES",
            "AMAZING GRACE",
            "DOO YOU HEAR WHAT I HEAR?",
            "CHAPPY KRIMAS",
            "IT'S THE MOST WONDERFUL TIME OF THE YEAR",
            "WHITE CHRISTMAS",
            "KIDZ IT'S CHRISTMAS",
            "FROSTED THE SNOWMAN",
            "TRUE END",
            "IT'S BEGINNING TO LOOK A LOT LIKE CHRISTMAS",
            "CAROL OF THE BELLS",
            "THE NUTCRACKER"
        ]
    },
    {
        "id": "1054036070672",
        "name": "【上海】《爱乐之城 书房沙龙烛光音乐会》",
        "city": "上海市",
        "venue": "中版书房",
        "time": "2026.06.13 周六 20:00",
        "price_min": 6,
        "price_max": 238,
        "link": "https://detail.damai.cn/item.htm?id=1054036070672",
        "tracks": [
            "1. 爱乐之城组曲",
            "2. 自由探戈",
            "3. 情迷Olivia",
            "4. 阿拉伯舞姿",
            "5. 爱尔兰人Irlaide",
            "6. 加勒比",
            "7. 马兰之托的夜",
            "8. 千年",
            "9. 艾乌Tico_Tico_no_fuba",
            "10. 人生的旋转木马",
            "11. 我们俩Two Of Us",
            "12. 情热天火",
            "13. 我的第七章"
        ]
    },
    {
        "id": "1053428560798",
        "name": "【上海】崔恩尔个人音乐会Oops!",
        "city": "上海市",
        "venue": "茉莉花剧场",
        "time": "2026.06.06-06.07",
        "price_min": 280,
        "price_max": 580,
        "link": "https://detail.damai.cn/item.htm?id=1053428560798",
        "tracks": []
    },
    {
        "id": "1053472176609",
        "name": "【上海】2026浦东精品剧目展演-王羽佳钢琴独奏音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.04 周四 19:30",
        "price_min": 80,
        "price_max": 80,
        "link": "https://detail.damai.cn/item.htm?id=1053472176609",
        "tracks": [
            "舒伯特 Schubert",
            "降E小调，极快板，选自《三首钢琴小品》，作品D. 946",
            "No.1 in E-flat minor, Allegro assai, from Drei Klavierstücke, D. 946",
            "降E大调，小快板，选自《三首钢琴小品》，作品D. 946",
            "No.2 in E-flat major, Allegretto, from Drei Klavierstücke, D. 946",
            "拉赫玛尼诺夫 Rachmaninoff",
            "雏菊，选自《六首歌曲》，作品38之3",
            "Daisies, excerpt from Six Romances, Op. 38 No. 3",
            "D大调前奏曲，作品23之4",
            "Prelude in D major, Op. 23 No. 4",
            "G小调前奏曲，作品23之5",
            "Prelude in G minor, Op. 23 No. 5",
            "巴赫/改编：拉赫玛尼诺夫 Bach/Arr. Rachmaninoff",
            "加沃特舞曲，选自E大调第3小提琴组曲, 作品BWV 1006",
            "Gavotte, excerpt from Partita in E major for violin, BWV 1006",
            "拉威尔 Ravel",
            "幽谷钟声，选自《镜子》组曲，作品43之5",
            "La vallée des cloches, excerpt from Miroirs, M. 43 No. 5",
            "索菲亚·古拜杜丽娜 Sofia Gubaidulina",
            "恰空 Chaconne",
            "托马斯·阿德斯 Thomas Adès",
            "《涂脂抹粉》音乐会改编曲",
            "Concert Paraphrase on Powder Her Face",
            "拉威尔 Ravel",
            "圆舞曲，作品M. 72",
            "La Valse, M. 72"
        ]
    },
    {
        "id": "1051667477860",
        "name": "【上海】王羽佳钢琴独奏音乐会",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.04 周四 19:30",
        "price_min": 880,
        "price_max": 1680,
        "link": "https://detail.damai.cn/item.htm?id=1051667477860",
        "tracks": [
            "降E小调，极快板，选自《三首钢琴小品》，作品D.946",
            "No.1 in E-flat minor, Allegro assai, from Drei Klavierstücke, D.946",
            "舒伯特",
            "Schubert",
            "降E大调，小快板，选自《三首钢琴小品》，作品D.946",
            "No.2 in E-flat major, Allegretto, from Drei Klavierstücke, D.946",
            "舒伯特",
            "Schubert",
            "雏菊，选自《六首歌曲》，作品38之3",
            "Daisies, excerpt from Six Romances, Op.38 No.3",
            "拉赫玛尼诺夫",
            "Rachmaninoff",
            "D大调前奏曲，作品23之4",
            "Prelude in D major, Op.23 No.4",
            "拉赫玛尼诺夫",
            "Rachmaninoff",
            "G小调前奏曲，作品23之5",
            "Prelude in G minor, Op.23 No.5",
            "拉赫玛尼诺夫",
            "Rachmaninoff",
            "加沃特舞曲，选自E大调第3小提琴组曲, 作品BWV 1006",
            "Gavotte, excerpt from Partita in E major for violin, BWV 1006",
            "巴赫",
            "Bach",
            "改编：拉赫玛尼诺夫",
            "Arr. Rachmaninoff",
            "中场休息",
            "Intermission",
            "幽谷钟声，选自《镜子》组曲，作品43之5",
            "La vallée des cloches, excerpt from Miroirs, M.43 No.5",
            "拉威尔",
            "Ravel",
            "恰空",
            "Chaconne",
            "索菲亚·古拜杜丽娜",
            "Sofia Gubaidulina",
            "《涂脂抹粉》音乐会改编曲",
            "Concert Paraphrase on Powder Her Face",
            "托马斯·阿德斯",
            "Thomas Adès",
            "圆舞曲，作品M.72",
            "La Valse, M.72",
            "拉威尔",
            "Ravel"
        ]
    },
    {
        "id": "1046586103759",
        "name": "【上海】《我用歌声拥抱祖国》——大型交响合唱音乐会",
        "city": "上海市",
        "venue": "云间剧院",
        "time": "2026.06.07 周日 14:30",
        "price_min": 80,
        "price_max": 180,
        "link": "https://detail.damai.cn/item.htm?id=1046586103759",
        "tracks": []
    },
    {
        "id": "1047722345731",
        "name": "【上海】且听天命《黑神话：悟空》全球音乐会",
        "city": "上海市",
        "venue": "北外滩友邦大剧院-大剧场",
        "time": "2026.06.07 周日",
        "price_min": 180,
        "price_max": 880,
        "link": "https://detail.damai.cn/item.htm?id=1047722345731",
        "tracks": [
            "英雄气概等时休",
            "这把火你看到了吗",
            "看见",
            "黄风起兮",
            "聋",
            "我也去当个天命人玩玩",
            "偶像即业障",
            "屁",
            "变化广无边",
            "慈悲颠倒何故",
            "勿听",
            "有经处有火",
            "不由己",
            "法天象地",
            "敢问路在何方",
            "云宫迅音",
            "未竟"
        ]
    },
    {
        "id": "1027669696248",
        "name": "【上海】《从管风琴经典到魔力好莱坞》- 英国管风琴明星安娜·拉普伍德首度亚洲巡演 上海站",
        "city": "上海市",
        "venue": "东方艺术中心-音乐厅",
        "time": "2026.06.24 周三 19:30",
        "price_min": 80,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1027669696248",
        "tracks": [
            "汉斯·季默∣圣杯骑士，选自电影《达·芬奇密码》",
            "菲利普·格拉斯∣疯狂冲刺",
            "巴赫/古诺∣圣母颂",
            "汉斯·季默∣玉米地追逐，选自电影《星际穿越》",
            "鲁多维科·艾奥迪∣体验",
            "尤金·吉古∣托卡塔",
            "霍华德·肖恩（拉普伍德改编）∣《指环王》组曲",
            "约翰·威廉姆斯（拉普伍德改编）∣宿命对决，选自电影《星球大战》",
            "蕾切尔·波特曼∣飞行",
            "奥利维亚·贝利∣光之极限",
            "汉斯·季默∣《加勒比海盗》组曲"
        ]
    },
    {
        "id": "1020907452447",
        "name": "【上海】布劳蒂甘早期钢琴独奏会丨上海交响乐团音乐季",
        "city": "上海市",
        "venue": "捷豹上海交响音乐厅-演艺厅",
        "time": "2026.06.06 周六 19:15",
        "price_min": 80,
        "price_max": 380,
        "link": "https://detail.damai.cn/item.htm?id=1020907452447",
        "tracks": [
            "贝多芬：降E大调第十三钢琴奏鸣曲，作品27之1「幻想曲风格的奏鸣曲」",
            "莫扎特：C大调「小星星」主题变奏曲，KV 265",
            "海顿：降E大调第六十二奏鸣曲，Hob.XVI:52「伦敦」",
            "莫扎特：a小调回旋曲，KV 511",
            "海顿：降E大调变奏曲，Hob.XVII:3",
            "贝多芬：升c小调第十四钢琴奏鸣曲，作品27之2「月光」"
        ]
    }
];
